### ISSUE TITLE
"pip install geotiff" doesn't install dependencies

### ISSUE THREAD

**Issue by jjramsey** [Open-Source-Agriculture/geotiff#10]
On geotiff's PyPi page, it says that "Installing this package is as easy as: 'pip install geotiff'". However, this isn't true. If I do that and try to run the Python statement "import geotiff", I get the error message, "ModuleNotFoundError: No module named 'shapely'". If I install shapely, I then get the error message "ModuleNotFoundError: No module named 'zarr'".

Of course, it's easy enough to install those packages manually, and once I do, the geotiff module imports without complaint, but it's still an annoyance.

**Comment by KipCrossing** [comment]
Hi, thanks for the feedback. The package is still in the early stages of development so there are bound to be things I overlooked without many active users.

I added the `install_requires` to the `setup.py` file so it should install the dependencies now :)

Update to VERSION = "0.1.1"


Let me know if you still have trouble.
